Update prod (#223)
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ideen <48538139+ideen1@users.noreply.github.com>
Co-authored-by: Hanna <144185720+hannagracec@users.noreply.github.com>
Co-authored-by: ideen1 <ibanijamali@gmail.com>
Co-authored-by: Justin Pham <113923596+justin-phxm@users.noreply.github.com>
Co-authored-by: hannagracec <hannacho847@gmail.com>
Co-authored-by: Natalie <natalie.yeung16@gmail.com>
Co-authored-by: Hooriya <121422181+riyeur@users.noreply.github.com>
Co-authored-by: Oluwafisayo Adabs <116133322+fisayoadabs@users.noreply.github.com>
Co-authored-by: Anthony <88424536+anthonyych4n@users.noreply.github.com>
Co-authored-by: emiko47 <113942291+emiko47@users.noreply.github.com>
Co-authored-by: sim <simarkandola51@gmail.com>
Co-authored-by: fionaa-truong <151110138+fionaa-truong@users.noreply.github.com>
Co-authored-by: anthonyych4n <anthony168c@gmail.com>
Co-authored-by: Aj Sallh <77182361+asallh@users.noreply.github.com>

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -1,50 +1,52 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# ESLint is a tool for identifying and reporting on patterns
-# found in ECMAScript/JavaScript code.
-# More details at https://github.com/eslint/eslint
-# and https://eslint.org
-
 name: ESLint
 
 on:
   push:
     branches: ["main"]
   pull_request:
-    # The branches below must be a subset of the branches above
     branches: ["main"]
   schedule:
     - cron: "25 21 * * 4"
 
 jobs:
   eslint:
-    name: Run eslint scanning
+    name: Run ESLint Scanning
     runs-on: ubuntu-latest
     permissions:
       contents: read
       security-events: write
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+      actions: read
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Install ESLint
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          npm install eslint@8.10.0
-          npm install @microsoft/eslint-formatter-sarif@2.1.7
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "install-command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "install-command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.install-command }}
 
       - name: Run ESLint
-        run: npx eslint .
-          --config .eslintrc.cjs
-          --ext .js,.jsx,.ts,.tsx
-      #     --format @microsoft/eslint-formatter-sarif
-      #     --output-file eslint-results.sarif
-      #   continue-on-error: false
-
-      # - name: Upload analysis results to GitHub
-      #   uses: github/codeql-action/upload-sarif@v2
-      #   with:
-      #     sarif_file: eslint-results.sarif
-      #     wait-for-processing: true
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} eslint . --ext .ts,.tsx
